
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GUION = 4;
  public static final int CADENA = 23;
  public static final int CONCATENACION = 10;
  public static final int CERRADURA_POSITIVA = 13;
  public static final int CERRADURA_BOOLEANA = 14;
  public static final int LETRA_MINUSCULA = 18;
  public static final int DOS_PUNTOS = 3;
  public static final int PORCENTAJE = 15;
  public static final int CARACTER = 22;
  public static final int SEPARADOR = 7;
  public static final int COMA = 6;
  public static final int CARACTERES_ESPECIALES = 21;
  public static final int PR_CONJ = 2;
  public static final int NUMEROS = 20;
  public static final int MAYOR = 5;
  public static final int EOF = 0;
  public static final int LETRA_MAYUSCULA = 19;
  public static final int DISYUNCION = 11;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 17;
  public static final int LLAVE_C = 9;
  public static final int LLAVE_A = 8;
  public static final int CERRADURA_KLEENE = 12;
  public static final int PUNTO_Y_COMA = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_CONJ",
  "DOS_PUNTOS",
  "GUION",
  "MAYOR",
  "COMA",
  "SEPARADOR",
  "LLAVE_A",
  "LLAVE_C",
  "CONCATENACION",
  "DISYUNCION",
  "CERRADURA_KLEENE",
  "CERRADURA_POSITIVA",
  "CERRADURA_BOOLEANA",
  "PORCENTAJE",
  "PUNTO_Y_COMA",
  "IDENTIFICADOR",
  "LETRA_MINUSCULA",
  "LETRA_MAYUSCULA",
  "NUMEROS",
  "CARACTERES_ESPECIALES",
  "CARACTER",
  "CADENA"
  };
}

