
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLA_SIMPLE = 21;
  public static final int GUION = 6;
  public static final int CADENA = 23;
  public static final int CONCATENACION = 15;
  public static final int CERRADURA_POSITIVA = 18;
  public static final int CONJUNTO = 2;
  public static final int ABRE_LLAVES = 3;
  public static final int BARRA = 13;
  public static final int VARIABLE = 24;
  public static final int MAYOR_QUE = 7;
  public static final int LETRA_MINUSCULA = 28;
  public static final int DOS_PUNTOS = 5;
  public static final int COMILLAS_DOBLES = 20;
  public static final int CARACTER = 14;
  public static final int COMA = 9;
  public static final int CIERRA_LLAVES = 4;
  public static final int CIERRA_INTERROGACION = 19;
  public static final int EOF = 0;
  public static final int LETRA_MAYUSCULA = 27;
  public static final int DISYUNCION = 16;
  public static final int NUMERO = 26;
  public static final int error = 1;
  public static final int ASCCI = 25;
  public static final int SALTO_LINEA = 22;
  public static final int VIRGULILLA = 11;
  public static final int PUNTO_COMA = 8;
  public static final int CERRADURA_KLEENE = 17;
  public static final int PORCENTAJES = 10;
  public static final int BARRA_INVERTIDA = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJUNTO",
  "ABRE_LLAVES",
  "CIERRA_LLAVES",
  "DOS_PUNTOS",
  "GUION",
  "MAYOR_QUE",
  "PUNTO_COMA",
  "COMA",
  "PORCENTAJES",
  "VIRGULILLA",
  "BARRA_INVERTIDA",
  "BARRA",
  "CARACTER",
  "CONCATENACION",
  "DISYUNCION",
  "CERRADURA_KLEENE",
  "CERRADURA_POSITIVA",
  "CIERRA_INTERROGACION",
  "COMILLAS_DOBLES",
  "COMILLA_SIMPLE",
  "SALTO_LINEA",
  "CADENA",
  "VARIABLE",
  "ASCCI",
  "NUMERO",
  "LETRA_MAYUSCULA",
  "LETRA_MINUSCULA"
  };
}

